algoritmo "Exercício 10"
var
   A, L, R1, R2: Real
inicio
      Escreva ("Digite aqui a altura de sua parede: ")
      Leia(A)
      Escreva ("Digite aqui a largura da sua parede: ")
      Leia(L)
             R1 <- (A * L)
      Escreval ("A altura e Largura de sua parede é de ", R1, "M²")
              R2 <- (A * L) / 2
      Escreva ("Você irá precisar de ", R2, "L de tinta para pintar toda a parede")

fimalgoritmo