Algoritmo "Exercicio05"
//Crie um programa que receba 1 valor e diga se esta no intervalo entre
//100 e 200.
Var
   N1:Inteiro
Inicio
      Escreva("Digite um número: ")
      Leia(N1)
      Se(N1 >= 100) e (N1 <= 200) entao
            Escreval("O valor ",N1, " está no intervalo entre 100 e 200.")
      Senao
           Escreval("O valor ",N1, " não está no intervalo entre 100 e 200.")
      FimSe
Fimalgoritmo