Algoritmo "Exercicio04"
//Crie um programa que leia dois valores inteiros diferentes, e informe
//qual é o maior.
Var
   N1,N2:Inteiro
Inicio
      Escreva("Digite um número: ")
      Leia(N1)
      Escreva("Digite outro número: ")
      Leia(N2)
      Se(N1 > N2) entao
            Escreval("O maior número é: ", N1)
      Senao
           Escreval("O maior número é: ", N2)
      FimSe
Fimalgoritmo