Algoritmo "SOMADOR"
//Algoritmo - Video Aula 03 - Aula Pratica 02
//Abordagem - Comandos de entrada e operadores
//Professor Gustavo Guanabara - Curso em video
//-----------------------------------------------
//Solicite dois numeros para o usuario e mostre a soma dele.
Var
 n, n2:Inteiro
 M:Real
Inicio
 Escreva ("Informe o primeiro número: ")
 Leia (n)
 Escreva ("Informe o segundo número: ")
 Leia (N2)
 M <- (n + n2) /2
 Escreva ("A média entre ", n, " e ", n2, " é igual a ", M)
Fimalgoritmo