Algoritmo "Contar de 10 até 0"
//Algoritmo - Video Aula 09 - Aula Prática 02
//Abordagem - Estrutura de Repetição parte 1 - Enquanto
//Professor Gustavo Guanabara - Curso em Video
//----------------------------------------------------
//Crie um programa que conte de 0 a 10
Var
 CONT: Inteiro
Inicio
 CONT <- 10
 Escreval ("------ CONTADOR ------")
 Enquanto (CONT >= 0) faca
          Escreval (CONT)
          CONT <- CONT - 1
 FimEnquanto
 Escreval ("Terminei de contar!")
 
Fimalgoritmo