Algoritmo "Contar de 0 a 10"
//Algoritmo - Video Aula 09 - Aula Prática 01
//Abordagem - Estrutura de Repetição parte 1 - Enquanto
//Professor Gustavo Guanabara - Curso em Video
//----------------------------------------------------
//Crie um programa que conte de 0 a 10
Var
 CONT: Inteiro
Inicio
 CONT <- 0
 Escreval ("------ CONTADOR ------")
 Enquanto (CONT <= 10) faca
          Escreval (CONT)
          CONT <- CONT + 1
 FimEnquanto
 Escreval ("Terminei de contar!")
 
Fimalgoritmo